name: Build Program

on:
  push:
  workflow_dispatch:
    inputs: 
      BuildBranch:
        description: 'The branch you want to build.' 
        required: true
        default: 'master'
      BuildConfiguration:
        description: 'The configuration for dotnet build.'
        required: true
        default: 'Release'
        type: choice
        options: 
          - Release
          - Debug
    
env:
  Configuration: ${{ github.event.inputs.BuildConfiguration || 'Release' }} 
  Branch: ${{ github.event.inputs.BuildBranch || 'master' }}
  Version: 0.2.8

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ env.Branch }}
        submodules: recursive
    - name: Setup .NET6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish
      run: dotnet publish .\src\OngekiFumenEditorPlugins.OngekiFumenSupport.csproj --no-restore -c ${{env.Configuration}} -o ./bin/githubActions/Plugins/OngekiFumenEditorPlugins.OngekiFumenSupport
    - name: Enum files
      run: Get-ChildItem -Recurse
    - uses: actions/upload-artifact@v3
      with:
        name: OngekiFumenEditorPlugins.OngekiFumenSupport_${{env.Branch}}_${{env.Configuration}}
        path: D:\a\OngekiFumenSupport\OngekiFumenSupport\bin\githubActions
